### ISSUE TITLE
Errors when running example code

### ISSUE THREAD

**Issue by d0dge** [jbytecode/rcaller#14]
I'm trying to integrate RCaller into a project but get an exception whenever calling "caller.getParser()".

For example, running the "Example2" code from https://github.com/jbytecode/rcaller/blob/master/RCaller/src/main/java/examples/Example2.java gives the following exception:

```
Exception in thread "main" java.lang.AbstractMethodError: gnu.xml.dom.DomElement.getTextContent()Ljava/lang/String;
    at com.github.rcaller.rstuff.ROutputParser.getAsStringArray(ROutputParser.java:175)
    at com.github.rcaller.rstuff.ROutputParser.getAsDoubleArray(ROutputParser.java:186)
    at examples.Example2.<init>(Example2.java:96)
    at examples.Example2.main(Example2.java:43)
```

I have RCaller 3.1 and R 3.3.1 installed.  What am I missing?

**Comment by jbytecode** [comment]
Example2 runs and passes in the current configuration. I could not figure out the problem with your results.
