### ISSUE TITLE
How to set path to R manually using script engine?

### ISSUE THREAD

**Issue by wongjoel** [jbytecode/rcaller#21]
As far as I understand, when trying to use `RCallerScriptEngine`, the location to the R executable is controlled by the value of `Globals.R_current`. I suggest that perhaps there could be a way to pass in the location of the R executable with a parameter instead of modifying the value of `Globals.R_current` directly to avoid the problem I describe below?

I am attempting to call an old version of R, which is not being detected automatically, so I've been trying to set the path to R manually. I've worked out how to do it with `RCaller` by using 
```
RCallerOptions options = RCallerOptions.create("C:\\Program Files (x86)\\R\\R-2.11.1\\bin\\Rscript.exe", "C:\\Program Files (x86)\\R\\R-2.11.1\\bin\\R.exe", FailurePolicy.RETRY_5, Long.MAX_VALUE, 100, RProcessStartUpOptions.create());
RCode code = RCode.create();
RCaller caller = RCaller.create(code, options);
```
but when I attempt to use `RCallerScriptEngine`, I can't work out the equivalent set up.

I tried to follow `RCallerScriptEngineExample1`, but upon attempting to access a field of the `Globals` class, I get an ExceptionInInitializerError.

In other words, when running the following line:
```
Globals.R_Current = "C:\\Program Files (x86)\\R\\R-2.11.1\\bin\\R.exe";
```
I get the following stack trace
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
        at examples.RCallerScriptEngineExample1.<init>(RCallerScriptEngineExample1.java:18)
        at examples.RCallerScriptEngineExample1.main(RCallerScriptEngineExample1.java:11)
        at Main.main(Main.java:10)
        ... 6 more
Caused by: java.lang.NullPointerException
        at java.util.Arrays.sort(Arrays.java:1246)
        at com.github.rcaller.util.Globals.<clinit>(Globals.java:65)
        ... 9 more
```
As can be seen in the stack trace, I'm using Maven, but I don't think that's the reason for the Null Pointer Exception.

Anyway, all that to ask if modifying `Globals.R_current` is the intended way to manually set the location of the R executable, and if it would be difficult to make it a parameter that can be passed into a constructor instead.

Thanks again,

**Comment by wongjoel** [comment]
I think this issue would be solved if we could solve issue #22
