### ISSUE TITLE
How to run "runAndReturnResult" multiple times in Java ?

### ISSUE THREAD

**Issue by VineelaKantamneni** [jbytecode/rcaller#64]
![Screenshot from 2021-06-10 11-59-44](https://user-images.githubusercontent.com/74599304/121476088-de57fe80-c9e3-11eb-9a71-6188086adf41.png)

Above is my java code as I am getting values from dataframe to a variable and getting it's values.So,I need to use the command "runAndReturnResult" multiple times.  While doing this I am getting below error.

0 = 2356040.74911315
1 = 2506554.65816997
2 = 2313497.11496627
3 = 2399868.1618223
Exception in thread "main" com.github.rcaller.exception.ExecutionException: Can not run /usr/local/bin/Rscript. Reason: java.lang.IllegalThreadStateException
	at com.github.rcaller.rstuff.RCaller.runRCode(RCaller.java:261)
	at com.github.rcaller.rstuff.RCaller.runAndReturnResult(RCaller.java:540)
	at estimate.hello.rCall(hello.java:88)
	at estimate.hello.main(hello.java:110)

---------------------------------------------------------
For first time it's running fine but for second time getting error.Please anyone helpme out to solve it.Thank you.

**Comment by jbytecode** [comment]
Since you are not reporting a bug, this is not a real issue so it is better to use some forums such like Stackoverflow.
